CafeWebApp.Web/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CafeWebApp.DomainModelEntity;
using CafeWebApp.InfrastructurePersistence.Repositories;

namespace CafeWebApp.Web.Controllers
{
    public class AdminController : Controller
    {
        //private AppDbContext db = new AppDbContext();
        private AdminRepository adminRepo = new AdminRepository();

        // GET: Admin
        public ActionResult LoginPage()
        {
            return View();
        }
        [HttpPost]
        public ActionResult LoginPage(User user)
        {
            //var checkAdmin = db.User.Where(u => u.Username == user.Username && u.Roles == Roles.Admin).SingleOrDefault();
            var checkAdmin = adminRepo.CheckAdmin(user);
            if (checkAdmin != null)
            {
                if (checkAdmin.Password != user.Password)
                {
                    ViewBag.Error = "Invalid Username or Password";
                    return View();
                }
                else
                {
                    Session["UserId"] = checkAdmin.Id;
                    return RedirectToAction("Index", user);
                }
            }
            else
            {
                ViewBag.Error = "Invalid Username or Password";
                return View();
            }
        }
        public ActionResult LogOut()
        {
            Session.Abandon();
            return RedirectToAction("LoginPage");
        }
        public ActionResult Index()
        {
            //return View(db.User.ToList());
            return View(adminRepo.GetUsers());
        }
        public ActionResult FoodMenu()
        {
            return View(adminRepo.GetFoods());
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //User user = db.User.Find(id);
            User user = adminRepo.GetUser(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        public ActionResult FoodDetails(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //Food food = db.Food.Find(id);
            Food food = adminRepo.GetFood(id);
            if (food == null)
            {
                return HttpNotFound();
            }
            return View(food);
        }

        // GET: Admin/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Username,Password,Roles")] User user)
        {
            if (ModelState.IsValid)
            {
                //var filterTable = db.Table.ToList();
                //var filterUsername = db.User.Where(u => u.Username == user.Username).SingleOrDefault();
                var filterTable = adminRepo.GetTables();
                var filterUsername = adminRepo.CheckUsername(user);
                if (user.Roles == Roles.Cashier && filterTable.Count() < 10)
                {
                    for (int i = 1; i < 11; i++)
                    {
                        Table table = new Table();
                        table.TableNumber = i;
                        table.TableStatus = TableStatus.Empty;
                        table.UserId = null;
                        //db.Table.Add(table);
                        adminRepo.AddTable(table);
                    }
                }
                if (filterUsername != null)
                {
                    ViewBag.Msg = "This username is already exist";
                    return View();
                }
                //db.User.Add(user);
                //db.SaveChanges();
                adminRepo.AddUser(user);
                return RedirectToAction("Index");
            }
            return View(user);
        }

        // GET: Admin/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //User user = db.User.Find(id);
            User user = adminRepo.GetUser(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Admin/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Username,Password,Roles")] User user)
        {
            if (ModelState.IsValid)
            {
                //db.Entry(user).State = EntityState.Modified;
                //db.SaveChanges();
                adminRepo.UpdateUser(user);
                return RedirectToAction("Index");
            }
            return View(user);
        }

        public ActionResult FoodCreate()
        {
            return View();
        }

        // POST: Admin/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult FoodCreate([Bind(Include = "FoodId,Category,FoodName,FoodPrice,Remarks")] Food food)
        {
            if (ModelState.IsValid)
            {
                //var filterFoodName = db.Food.Where(f => f.FoodName == food.FoodName).SingleOrDefault();
                var filterFoodName = adminRepo.CheckFoodName(food);
                if (filterFoodName != null)
                {
                    ViewBag.Msg = "This Food is already exist";
                    return View();
                }
                //db.Food.Add(food);
                //db.SaveChanges();
                adminRepo.AddFood(food);
                return RedirectToAction("FoodMenu");
            }
            return View(food);
        }

        public ActionResult FoodEdit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //Food food = db.Food.Find(id);
            Food food = adminRepo.GetFood(id);
            if (food == null)
            {
                return HttpNotFound();
            }
            return View(food);
        }
        [HttpPost]
        public ActionResult FoodEdit([Bind(Include = "FoodId,Category,FoodName,FoodPrice,Remarks")] Food food)
        {
            if (ModelState.IsValid)
            {
                //db.Entry(food).State = EntityState.Modified;
                //db.SaveChanges();
                adminRepo.UpdateFood(food);
                return RedirectToAction("FoodMenu");
            }
            return View(food);
        }

        // GET: Admin/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //User user = db.User.Find(id);
            User user = adminRepo.GetUser(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Admin/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            //User user = db.User.Find(id);
            //db.User.Remove(user);
            //db.SaveChanges();
            User user = adminRepo.GetUser(id);
            adminRepo.RemoveUser(user);
            return RedirectToAction("Index");
        }

        public ActionResult FoodDelete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //Food food = db.Food.Find(id);
            Food food = adminRepo.GetFood(id);
            if (food == null)
            {
                return HttpNotFound();
            }
            return View(food);
        }

        [HttpPost, ActionName("FoodDelete")]
        [ValidateAntiForgeryToken]
        public ActionResult FoodDeleteConfirmed(int id)
        {
            //Food food = db.Food.Find(id);
            //db.Food.Remove(food);
            //db.SaveChanges();
            Food food = adminRepo.GetFood(id);
            adminRepo.RemoveFood(food);
            return RedirectToAction("FoodMenu");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                //db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CafeWebApp.Web/Controllers/CashierController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CafeWebApp.DomainModelEntity;
using CafeWebApp.InfrastructurePersistence.Repositories;

namespace CafeWebApp.Web.Controllers
{
    public class CashierController : Controller
    {
        //private AppDbContext db = new AppDbContext();
        private CashierRepository cashierRepo = new CashierRepository();
        private AdminRepository adminRepo = new AdminRepository();

        public ActionResult LoginPage()
        {
            return View();
        }
        [HttpPost]
        public ActionResult LoginPage(User user)
        {
            //var checkCashier = db.User.Where(u => u.Username == user.Username && u.Roles == Roles.Cashier).SingleOrDefault();
            var checkCashier = cashierRepo.CheckCashier(user);

            if (checkCashier != null)
            {
                if (checkCashier.Password != user.Password)
                {
                    ViewBag.Error = "Invalid Username or Password";
                    return View();
                }
                else
                {
                    Session["UserId"] = checkCashier.Id;
                    return RedirectToAction("Index", user);
                }
            }
            else
            {
                ViewBag.Error = "Invalid Username or Password";
                return View();
            }
        }
        public ActionResult LogOut()
        {
            Session.Abandon();
            return RedirectToAction("LoginPage");
        }
        // GET: Cashier
        public ActionResult Index()
        {
            //var table = db.Table.Include(t => t.User);
            //return View(table.ToList());
            return View(cashierRepo.GetTables());
        }

        // GET: Cashier/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //Table table = db.Table.Find(id);
            Table table = cashierRepo.GetTable(id);
            if (table == null)
            {
                return HttpNotFound();
            }
            return View(table);
        }

        // GET: Cashier/Create
        public ActionResult Create()
        {
            //ViewBag.UserId = new SelectList(db.User, "Id", "Username");
            return View();
        }

        // POST: Cashier/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TableId,TableStatus,TableNumber,UserId")] Table table)
        {
            if (ModelState.IsValid)
            {
                //db.Table.Add(table);
                //db.SaveChanges();
                return RedirectToAction("Index");
            }

            //ViewBag.UserId = new SelectList(db.User, "Id", "Username", table.UserId);
            return View(table);
        }

        // GET: Cashier/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //Table table = db.Table.Find(id);
            Table table = cashierRepo.GetTable(id);
            if (table == null)
            {
                return HttpNotFound();
            }
            //ViewBag.UserId = new SelectList(db.User, "Id", "Username", table.UserId);
            ViewBag.UserId = new SelectList(adminRepo.GetUsers(), "Id", "Username", table.UserId);
            return View(table);
        }

        // POST: Cashier/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TableId,TableStatus,TableNumber,UserId")] Table table)
        {
            if (ModelState.IsValid)
            {
                //db.Entry(table).State = EntityState.Modified;
                //db.SaveChanges();
                if (table.TableStatus == TableStatus.Empty)
                {
                    table.UserId = null;
                }
                cashierRepo.UpdateTable(table);
                return RedirectToAction("Index");
                
            }
            //ViewBag.UserId = new SelectList(db.User, "Id", "Username", table.UserId);
            ViewBag.UserId = new SelectList(adminRepo.GetUsers(), "Id", "Username", table.UserId);
            return View(table);
        }

        // GET: Cashier/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //Table table = db.Table.Find(id);
            Table table = cashierRepo.GetTable(id);
            if (table == null)
            {
                return HttpNotFound();
            }
            return View(table);
        }

        // POST: Cashier/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            //Table table = db.Table.Find(id);
            //db.Table.Remove(table);
            //db.SaveChanges();
            Table table = cashierRepo.GetTable(id);
            cashierRepo.RemoveTable(table);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                //db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CafeWebApp.Web/Views/Shared/AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Cafe(Admin)", "LoginPage", "Admin", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("User", "Index", "Admin")</li>
                    <li>@Html.ActionLink("Menu", "FoodMenu", "Admin")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Cafe</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

CafeWebApp.Web/Views/Shared/CashierLayout.cshtml
<!DOCTYPE html>
@if (Session["UserId"] == null)
{
    Session.Abandon();
    Response.Redirect("LoginPage");
}
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Cafe(Cashier)", "LoginPage", "Cashier", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Tables", "Index", "Cashier")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Cafe</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

CafeWebApp.Web/Views/Shared/CustomerLayout.cshtml
<!DOCTYPE html>
@if (Session["UserId"] == null)
{
    Session.Abandon();
    Response.Redirect("LoginPage");
}
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Cafe(Customer)", "LoginPage", "Customer", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("FoodMenu", "FoodMenu", "Customer")</li>
                    <li>@Html.ActionLink("Cart", "Cartlist", "Customer")</li>
                    <li>@Html.ActionLink("Log Out", "LogOut", "Customer")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Cafe</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

CafeWebApp.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
@if (Session["UserId"] == null)
{
    Session.Abandon();
    Response.Redirect("LoginPage");
}
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Cafe(Admin)", "LoginPage", "Admin", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("User", "Index", "Admin")</li>
                    <li>@Html.ActionLink("Menu", "FoodMenu", "Admin")</li>
                    <li>@Html.ActionLink("Log Out", "LogOut", "Admin")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Cafe</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

CafeWebApp.Web/Views/Shared/_Layout2.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Cafe(Customer)", "LoginPage", "Customer", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("FoodMenu", "FoodMenu", "Customer")</li>
                    <li>@Html.ActionLink("Cart", "Cartlist", "Customer")</li>
                    <li>@Html.ActionLink("Log Out", "LogOut", "Customer")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Cafe</p>
        </footer>
    </div>


    @RenderSection("scripts", required: false)
</body>
</html>

CafeWebApp.Web/Views/Shared/_Layout3.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Cafe(Cashier)", "LoginPage", "Cashier", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Tables", "Index", "Cashier")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Cafe</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>